# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_inspector.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets

class Ui_data_inspection_widget(object):
    def setupUi(self, data_inspection_widget):
        data_inspection_widget.setObjectName("data_inspection_widget")
        data_inspection_widget.resize(859, 630)
        self.horizontalLayout = QtWidgets.QHBoxLayout(data_inspection_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_layout = QtWidgets.QHBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.image_graphics_view = QtWidgets.QGraphicsView(data_inspection_widget)
        self.image_graphics_view.setObjectName("image_graphics_view")
        self.main_layout.addWidget(self.image_graphics_view)
        self.image_slider = QtWidgets.QScrollBar(data_inspection_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_slider.sizePolicy().hasHeightForWidth())
        self.image_slider.setSizePolicy(sizePolicy)
        self.image_slider.setOrientation(QtCore.Qt.Vertical)
        self.image_slider.setInvertedAppearance(False)
        self.image_slider.setObjectName("image_slider")
        self.main_layout.addWidget(self.image_slider)
        self.control_panel_widget = QtWidgets.QWidget(data_inspection_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_panel_widget.sizePolicy().hasHeightForWidth())
        self.control_panel_widget.setSizePolicy(sizePolicy)
        self.control_panel_widget.setObjectName("control_panel_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.control_panel_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.data_display_groupbox = QtWidgets.QGroupBox(self.control_panel_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_display_groupbox.sizePolicy().hasHeightForWidth())
        self.data_display_groupbox.setSizePolicy(sizePolicy)
        self.data_display_groupbox.setFlat(False)
        self.data_display_groupbox.setObjectName("data_display_groupbox")
        self.gridLayout = QtWidgets.QGridLayout(self.data_display_groupbox)
        self.gridLayout.setObjectName("gridLayout")
        self.ground_truth_combobox = QtWidgets.QComboBox(self.data_display_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ground_truth_combobox.sizePolicy().hasHeightForWidth())
        self.ground_truth_combobox.setSizePolicy(sizePolicy)
        self.ground_truth_combobox.setObjectName("ground_truth_combobox")
        self.gridLayout.addWidget(self.ground_truth_combobox, 0, 1, 1, 1)
        self.ground_truth_checkbox = QtWidgets.QCheckBox(self.data_display_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ground_truth_checkbox.sizePolicy().hasHeightForWidth())
        self.ground_truth_checkbox.setSizePolicy(sizePolicy)
        self.ground_truth_checkbox.setObjectName("ground_truth_checkbox")
        self.gridLayout.addWidget(self.ground_truth_checkbox, 0, 0, 1, 1)
        self.predicted_checkbox = QtWidgets.QCheckBox(self.data_display_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predicted_checkbox.sizePolicy().hasHeightForWidth())
        self.predicted_checkbox.setSizePolicy(sizePolicy)
        self.predicted_checkbox.setObjectName("predicted_checkbox")
        self.gridLayout.addWidget(self.predicted_checkbox, 1, 0, 1, 1)
        self.predicted_combobox = QtWidgets.QComboBox(self.data_display_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predicted_combobox.sizePolicy().hasHeightForWidth())
        self.predicted_combobox.setSizePolicy(sizePolicy)
        self.predicted_combobox.setObjectName("predicted_combobox")
        self.gridLayout.addWidget(self.predicted_combobox, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.data_display_groupbox)
        self.table_tab_widget = QtWidgets.QTabWidget(self.control_panel_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_tab_widget.sizePolicy().hasHeightForWidth())
        self.table_tab_widget.setSizePolicy(sizePolicy)
        self.table_tab_widget.setObjectName("table_tab_widget")
        self.ground_truth_tab = QtWidgets.QWidget()
        self.ground_truth_tab.setObjectName("ground_truth_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ground_truth_tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ground_truth_table_view = QtWidgets.QTableView(self.ground_truth_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ground_truth_table_view.sizePolicy().hasHeightForWidth())
        self.ground_truth_table_view.setSizePolicy(sizePolicy)
        self.ground_truth_table_view.setMouseTracking(True)
        self.ground_truth_table_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ground_truth_table_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ground_truth_table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ground_truth_table_view.setObjectName("ground_truth_table_view")
        self.ground_truth_table_view.horizontalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_2.addWidget(self.ground_truth_table_view)
        self.table_tab_widget.addTab(self.ground_truth_tab, "")
        self.predicted_tab = QtWidgets.QWidget()
        self.predicted_tab.setObjectName("predicted_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.predicted_tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.predicted_table_view = QtWidgets.QTableView(self.predicted_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predicted_table_view.sizePolicy().hasHeightForWidth())
        self.predicted_table_view.setSizePolicy(sizePolicy)
        self.predicted_table_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.predicted_table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.predicted_table_view.setObjectName("predicted_table_view")
        self.verticalLayout_3.addWidget(self.predicted_table_view)
        self.table_tab_widget.addTab(self.predicted_tab, "")
        self.verticalLayout.addWidget(self.table_tab_widget)
        self.probability_slider = QtWidgets.QSlider(self.control_panel_widget)
        self.probability_slider.setAutoFillBackground(False)
        self.probability_slider.setMaximum(100)
        self.probability_slider.setSliderPosition(50)
        self.probability_slider.setOrientation(QtCore.Qt.Horizontal)
        self.probability_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.probability_slider.setObjectName("probability_slider")
        self.verticalLayout.addWidget(self.probability_slider)
        self.main_layout.addWidget(self.control_panel_widget)
        self.horizontalLayout.addLayout(self.main_layout)

        self.retranslateUi(data_inspection_widget)
        self.table_tab_widget.setCurrentIndex(1)
        self.ground_truth_checkbox.stateChanged['int'].connect(self.image_graphics_view.deleteLater)
        self.predicted_checkbox.stateChanged['int'].connect(self.image_graphics_view.deleteLater)
        self.ground_truth_table_view.activated['QModelIndex'].connect(self.image_graphics_view.deleteLater)
        self.predicted_table_view.activated['QModelIndex'].connect(self.image_graphics_view.deleteLater)
        self.probability_slider.valueChanged['int'].connect(self.image_graphics_view.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(data_inspection_widget)

    def retranslateUi(self, data_inspection_widget):
        _translate = QtCore.QCoreApplication.translate
        data_inspection_widget.setWindowTitle(_translate("data_inspection_widget", "Form"))
        self.image_slider.setToolTip(_translate("data_inspection_widget", "Scroll through images"))
        self.data_display_groupbox.setTitle(_translate("data_inspection_widget", "Displayed Data"))
        self.ground_truth_combobox.setToolTip(_translate("data_inspection_widget", "Select ground truth marker"))
        self.ground_truth_checkbox.setToolTip(_translate("data_inspection_widget", "Show ground truth data"))
        self.ground_truth_checkbox.setText(_translate("data_inspection_widget", "Ground Truth"))
        self.predicted_checkbox.setToolTip(_translate("data_inspection_widget", "Show predicted data"))
        self.predicted_checkbox.setText(_translate("data_inspection_widget", "Predicted"))
        self.predicted_combobox.setToolTip(_translate("data_inspection_widget", "Select predicted marker"))
        self.table_tab_widget.setTabText(self.table_tab_widget.indexOf(self.ground_truth_tab), _translate("data_inspection_widget", "Ground Truth"))
        self.table_tab_widget.setTabText(self.table_tab_widget.indexOf(self.predicted_tab), _translate("data_inspection_widget", "Predicted"))
        self.probability_slider.setToolTip(_translate("data_inspection_widget", "Set probability"))

