# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_inspection_dialog2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_file_inspection_dialog(object):
    def setupUi(self, file_inspection_dialog):
        file_inspection_dialog.setObjectName("file_inspection_dialog")
        file_inspection_dialog.resize(680, 560)
        self.verticalLayout = QtWidgets.QVBoxLayout(file_inspection_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_widget = QtWidgets.QWidget(file_inspection_dialog)
        self.main_widget.setObjectName("main_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_structure_groupbox = QtWidgets.QGroupBox(self.main_widget)
        self.file_structure_groupbox.setObjectName("file_structure_groupbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.file_structure_groupbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.file_structure_tree_view = QtWidgets.QTreeView(self.file_structure_groupbox)
        self.file_structure_tree_view.setMidLineWidth(0)
        self.file_structure_tree_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.file_structure_tree_view.setDragEnabled(True)
        self.file_structure_tree_view.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.file_structure_tree_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.file_structure_tree_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.file_structure_tree_view.setObjectName("file_structure_tree_view")
        self.file_structure_tree_view.header().setVisible(False)
        self.verticalLayout_3.addWidget(self.file_structure_tree_view)
        self.horizontalLayout.addWidget(self.file_structure_groupbox)
        self.data_info_groupbox = QtWidgets.QGroupBox(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_info_groupbox.sizePolicy().hasHeightForWidth())
        self.data_info_groupbox.setSizePolicy(sizePolicy)
        self.data_info_groupbox.setObjectName("data_info_groupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.data_info_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.data_info_table_view = QtWidgets.QTableView(self.data_info_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_info_table_view.sizePolicy().hasHeightForWidth())
        self.data_info_table_view.setSizePolicy(sizePolicy)
        self.data_info_table_view.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.data_info_table_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.data_info_table_view.setTabKeyNavigation(False)
        self.data_info_table_view.setDragDropOverwriteMode(False)
        self.data_info_table_view.setAlternatingRowColors(True)
        self.data_info_table_view.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.data_info_table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.data_info_table_view.setShowGrid(True)
        self.data_info_table_view.setGridStyle(QtCore.Qt.DotLine)
        self.data_info_table_view.setObjectName("data_info_table_view")
        self.data_info_table_view.horizontalHeader().setCascadingSectionResizes(True)
        self.data_info_table_view.horizontalHeader().setDefaultSectionSize(100)
        self.data_info_table_view.horizontalHeader().setHighlightSections(True)
        self.data_info_table_view.horizontalHeader().setMinimumSectionSize(25)
        self.data_info_table_view.horizontalHeader().setStretchLastSection(True)
        self.data_info_table_view.verticalHeader().setVisible(True)
        self.verticalLayout_2.addWidget(self.data_info_table_view)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.images_groupbox = QtWidgets.QGroupBox(self.data_info_groupbox)
        self.images_groupbox.setObjectName("images_groupbox")
        self.gridLayout = QtWidgets.QGridLayout(self.images_groupbox)
        self.gridLayout.setObjectName("gridLayout")
        self.images_list_view = QtWidgets.QListView(self.images_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.images_list_view.sizePolicy().hasHeightForWidth())
        self.images_list_view.setSizePolicy(sizePolicy)
        self.images_list_view.setAcceptDrops(True)
        self.images_list_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.images_list_view.setDragEnabled(False)
        self.images_list_view.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.images_list_view.setAlternatingRowColors(True)
        self.images_list_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.images_list_view.setObjectName("images_list_view")
        self.gridLayout.addWidget(self.images_list_view, 0, 0, 1, 2)
        self.images_sort_button = QtWidgets.QPushButton(self.images_groupbox)
        self.images_sort_button.setObjectName("images_sort_button")
        self.gridLayout.addWidget(self.images_sort_button, 1, 0, 1, 1)
        self.images_clear_button = QtWidgets.QPushButton(self.images_groupbox)
        self.images_clear_button.setObjectName("images_clear_button")
        self.gridLayout.addWidget(self.images_clear_button, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.images_groupbox)
        self.roi_groupbox = QtWidgets.QGroupBox(self.data_info_groupbox)
        self.roi_groupbox.setObjectName("roi_groupbox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.roi_groupbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.roi_list_view = QtWidgets.QListView(self.roi_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roi_list_view.sizePolicy().hasHeightForWidth())
        self.roi_list_view.setSizePolicy(sizePolicy)
        self.roi_list_view.setAcceptDrops(True)
        self.roi_list_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.roi_list_view.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.roi_list_view.setAlternatingRowColors(True)
        self.roi_list_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.roi_list_view.setObjectName("roi_list_view")
        self.gridLayout_2.addWidget(self.roi_list_view, 0, 0, 1, 2)
        self.roi_clear_button = QtWidgets.QPushButton(self.roi_groupbox)
        self.roi_clear_button.setObjectName("roi_clear_button")
        self.gridLayout_2.addWidget(self.roi_clear_button, 1, 1, 1, 1)
        self.roi_sort_button = QtWidgets.QPushButton(self.roi_groupbox)
        self.roi_sort_button.setObjectName("roi_sort_button")
        self.gridLayout_2.addWidget(self.roi_sort_button, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.roi_groupbox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.data_info_groupbox)
        self.verticalLayout.addWidget(self.main_widget)
        self.button_box = QtWidgets.QDialogButtonBox(file_inspection_dialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(file_inspection_dialog)
        self.button_box.accepted.connect(file_inspection_dialog.accept)
        self.button_box.rejected.connect(file_inspection_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(file_inspection_dialog)

    def retranslateUi(self, file_inspection_dialog):
        _translate = QtCore.QCoreApplication.translate
        file_inspection_dialog.setWindowTitle(_translate("file_inspection_dialog", "Dialog"))
        self.file_structure_groupbox.setTitle(_translate("file_inspection_dialog", "File Structure"))
        self.data_info_groupbox.setTitle(_translate("file_inspection_dialog", "Data Info"))
        self.images_groupbox.setTitle(_translate("file_inspection_dialog", "Images"))
        self.images_list_view.setToolTip(_translate("file_inspection_dialog", "Drop image data here"))
        self.images_sort_button.setText(_translate("file_inspection_dialog", "Sort"))
        self.images_clear_button.setText(_translate("file_inspection_dialog", "Clear"))
        self.roi_groupbox.setTitle(_translate("file_inspection_dialog", "ROI"))
        self.roi_list_view.setToolTip(_translate("file_inspection_dialog", "Drop ROI data here"))
        self.roi_clear_button.setText(_translate("file_inspection_dialog", "Clear"))
        self.roi_sort_button.setText(_translate("file_inspection_dialog", "Sort"))

